name: Post Blog to WordPress

on:
  schedule:
    - cron: "30 8 * * *"  # Daily at 1:00 PM EDT / 10:00 AM MST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  post-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python environment
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libjpeg-dev zlib1g-dev libfreetype6-dev
          python3 -m venv .venv

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/generate_video_heygen.py', '**/edit_and_merge_video.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          .venv/bin/pip install --upgrade pip setuptools
          .venv/bin/pip install --no-cache-dir \
            pytz requests python-dotenv openai>=1.0.0 \
            ffmpeg-python natsort pillow==9.5.0 imageio==2.31.1 imageio-ffmpeg==0.4.8 \
            moviepy==1.0.3 yfinance feedparser \
            google-cloud-texttospeech gtts

      - name: Verify ffmpeg-python is importable
        run: .venv/bin/python -c "import ffmpeg; print('✅ ffmpeg-python works')"

      # 🆕 Market data fetch + log
      - name: Fetch market data and save snapshot
        run: .venv/bin/python market_snapshot_fetcher.py

      # 1️⃣ Blog generation using final.py
      - name: Run blog and summary generator
        run: .venv/bin/python final.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WP_USERNAME:     ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_SITE_URL:     ${{ secrets.WP_SITE_URL }}

      # 🔐 Write Google credentials to file
      - name: Write Google credentials to file
        run: echo "$GOOGLE_CREDENTIALS_JSON" > google-credentials.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Verify Google Cloud credentials
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/google-credentials.json"
          .venv/bin/python -c "from google.cloud import texttospeech; client = texttospeech.TextToSpeechClient(); print('✅ Google Cloud authentication works')"

      - name: Generate blog voiceover (Wavenet)
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/google-credentials.json"
          .venv/bin/python generate_audio_from_blog.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$(pwd)/google-credentials.json"

      - name: Upload blog audio to WordPress
        run: .venv/bin/python upload_audio_and_embed.py
        env:
          WP_USERNAME:     ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_SITE_URL:     ${{ secrets.WP_SITE_URL }}

      # 3️⃣ Video script + voiceover
      - name: Generate 20s video narration
        run: .venv/bin/python generate_video_prompt.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate video voiceover
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/google-credentials.json"
          .venv/bin/python generate_audio_for_video.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$(pwd)/google-credentials.json"

      # 4️⃣ Visuals from DALL·E
      - name: Generate visual prompts
        run: .venv/bin/python generate_visual_prompts.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate AI images
        run: .venv/bin/python generate_ai_images.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # 5️⃣ Generate avatar video using HeyGen API
      - name: Generate avatar video
        run: .venv/bin/python generate_video_heygen.py
        env:
          HEYGEN_API_KEY: ${{ secrets.HEYGEN_API }}

      - name: Save generated avatar video immediately
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add avatar_video.mp4
          git commit -m "Save generated avatar_video.mp4 [skip ci]" || echo "No avatar video changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push

      # 6️⃣ Edit avatar video with AI-generated images
      - name: Merge avatar video and overlay images
        run: .venv/bin/python edit_and_merge_video.py

      - name: Save generated final video immediately
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add video_output.mp4
          git commit -m "Save generated video_output.mp4 [skip ci]" || echo "No video changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push

      - name: Upload video to WordPress
        run: .venv/bin/python upload_video_to_wp.py
        env:
          WP_USERNAME:     ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_SITE_URL:     ${{ secrets.WP_SITE_URL }}

      # 7️⃣ YouTube integration
      - name: Install YouTube uploader dependencies
        run: .venv/bin/pip install google-auth google-auth-oauthlib google-api-python-client

      - name: Restore YouTube token
        run: echo "$YOUTUBE_TOKEN_B64" | base64 -d > youtube_token.pkl
        env:
          YOUTUBE_TOKEN_B64: ${{ secrets.YOUTUBE_TOKEN }}

      - name: Upload video to YouTube Shorts
        run: .venv/bin/python upload_to_youtube.py

      # 8️⃣ Save generated AI images to repo
      - name: Save AI-generated images to repo
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add ai_images/*.png
          git commit -m "Save AI-generated scene images [skip ci]" || echo "No AI image changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push

      # 9️⃣ Commit history logs
      - name: Commit history logs
        if: success()
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add blog_history.txt market_snapshot_log.jsonl video_prompt_history.txt visual_prompt_history.txt
          git commit -m "Update history logs [skip ci]" || echo "No history changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
